other_python_pkgs:
  - build-essential
  - libxslt1-dev
  - libffi-dev
  - libjpeg-dev
  - libxml2-dev
  - libxslt-dev
  - libyaml-dev
  - libpq-dev
  - libreadline-gplv2-dev
  - libncursesw5-dev
  - libssl-dev
  - libsqlite3-dev
  - tk-dev
  - libgdbm-dev
  - libc6-dev
  - libbz2-dev
  - libblas-dev
  - liblapack-dev
  - libatlas-base-dev
  - python-passlib
