---
# Add repository for java from ppa
- name: update apt repo
  apt_repository: repo='ppa:webupd8team/java' state=present
  tags:
    - java

# Accept the license
- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  tags:
    - java


# Update repositories cache and install "java" package and set default for environment
- name: Install Oracle Java 8
  become: yes
  apt: name={{item}} state=latest update_cache=yes
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
  tags:
    - java
