---
# Postgres create postgres db

- name: Install postgresql packages
  apt: pkg={{ item }} state=latest
  with_items:
    - postgresql
    - postgresql-contrib
    - postgresql-client
    - libpq-dev
  tags: postgres

- name: Install postgresql python bindings
  pip:
    name: psycopg2
  tags: postgres

- name: Create database
  become_user: postgres
  postgresql_db:
    name: "{{ sentry_db_name }}"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'
    state: present
  tags: postgres

- name: Grant access for database to user
  become_user: postgres
  postgresql_user:
    name: "{{ sentry_db_user }}"
    password: "{{ sentry_db_password }}"
    role_attr_flags: "CREATEDB,SUPERUSER"
  tags: postgres
